#!/bin/bash
# Based on iBeacon Scan by Radius Networks

HCI="hci0"

BARE=""
PARSE=""

while getopts ":i:pb" opt; do
  case $opt in
    i)
        HCI=$OPTARG
      ;;
    b)
        #bare outpùt (easyly parseable)
        BARE="1"
      ;;
    p)
        PARSE="1"
      ;;
    h)
      echo "Usage:"
      echo "$0 -i hciN [-b] [-p]"
      exit 0
      ;;
    :)
      exit 1
      ;;
  esac
done

if [[ "$PARSE" == "1" ]]; then
  packet=""
  capturing=""
  count=0
  while read line
  do
    count=$[count + 1]
    if [ "$capturing" ]; then
      if [[ $line =~ ^[0-9a-fA-F]{2}\ [0-9a-fA-F] ]]; then
        packet="$packet $line"
      else
        if [[ $packet =~ ^04\ 3E\ 2A\ 02\ 01\ .{26}\ 02\ 01\ .{14}\ 02\ 15 ]]; then
          UUID=`echo $packet | sed 's/^.\{69\}\(.\{47\}\).*$/\1/'`
          MAJOR=`echo $packet | sed 's/^.\{117\}\(.\{5\}\).*$/\1/'`
          MINOR=`echo $packet | sed 's/^.\{123\}\(.\{5\}\).*$/\1/'`
          POWER=`echo $packet | sed 's/^.\{129\}\(.\{2\}\).*$/\1/'`
          UUID=`echo $UUID | sed -e 's/\ //g' -e 's/^\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)\(.\{12\}\)$/\1-\2-\3-\4-\5/'`
          MAJOR=`echo $MAJOR | sed 's/\ //g'`
          MAJOR=`echo "ibase=16; $MAJOR" | bc`
          MINOR=`echo $MINOR | sed 's/\ //g'`
          MINOR=`echo "ibase=16; $MINOR" | bc`
          POWER=`echo "ibase=16; $POWER" | bc`
          POWER=$[POWER - 256]
          if [[ "$BARE" == "1" ]]; then
            echo "$UUID $MAJOR $MINOR $POWER"
          else
            echo "UUID: $UUID MAJOR: $MAJOR MINOR: $MINOR POWER: $POWER"
          fi
        fi
        capturing=""
        packet=""
      fi
    fi

    if [ ! "$capturing" ]; then
      if [[ $line =~ ^\> ]]; then
        packet=`echo $line | sed 's/^>.\(.*$\)/\1/'`
        capturing=1
      fi
    fi
  done
else
  hcitool -i $HCI lescan --duplicates 1>/dev/null &
  if [ "$(pidof hcitool)" ]; then
    hcidump -i $HCI --raw | ./$0 -i $HCI -p $1
  fi

fi
